sudo: required
services:
  - docker

before_install:
  - docker build -t ranaivoson0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ranaivoson0/react-test npm test -- --coverage

after_success:
  - docker build -t ranaivoson0/multi-client ./client
  - docker build -t ranaivoson0/multi-nginx ./nginx
  - docker build -t ranaivoson0/multi-server ./server
  - docker build -t ranaivoson0/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to dockerhub
  - docker push ranaivoson0/multi-client
  - docker push ranaivoson0/multi-nginx
  - docker push ranaivoson0/multi-server
  - docker push ranaivoson0/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-147763538318
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY